# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiwAgQjCSBwxEg5S9rJc67jOnYAE-rtf
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from io import BytesIO
import warnings
import traceback

warnings.filterwarnings("ignore")

# ============================================================================
# BLOCO DE CAPTURA DE ERROS
# ============================================================================

try:
    # ============================================================================
    # CONFIGURAÇÃO DA PÁGINA STREAMLIT
    # ============================================================================
    st.set_page_config(
        page_title="Dashboard PNAD/CAGED",
        page_icon="📊",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    st.markdown("""
        <style>
        .main { padding: 2rem; }
        .stMetric { background-color: #f0f2f6; padding: 1rem; border-radius: 0.5rem; }
        </style>
        """, unsafe_allow_html=True)

    # ============================================================================
    # TÍTULO
    # ============================================================================
    st.title("📊 Dashboard Interativo PNAD/CAGED")
    st.markdown("""
        **Análise de Salários, Movimentação e Diversidade no Mercado de Trabalho Brasileiro**
    """)

    # ============================================================================
    # CARREGAMENTO DE DADOS
    # ============================================================================
    @st.cache_data(ttl=3600)
    def carregar_dados_github():
        usuario_github = "pesquisaitr-cmd"
        repo_github = "PNAD"
        branch = "main"
        url_df_final = f"https://raw.githubusercontent.com/{usuario_github}/{repo_github}/{branch}/dados/df_final.parquet"
        url_df_inpc = f"https://raw.githubusercontent.com/{usuario_github}/{repo_github}/{branch}/dados/df_inpc.parquet"
        df_final = pd.read_parquet(url_df_final)
        df_inpc = pd.read_parquet(url_df_inpc)
        return df_final, df_inpc

    df_final, df_inpc = carregar_dados_github()

    # ============================================================================
    # PRÉ-PROCESSAMENTO DE DADOS
    # ============================================================================
    if "Anomes" not in df_inpc.columns:
        if "ano" in df_inpc.columns and "mes" in df_inpc.columns:
            df_inpc["Anomes"] = df_inpc["ano"].astype(str) + df_inpc["mes"].astype(str).str.zfill(2)
        else:
            st.error("❌ df_inpc não possui as colunas esperadas (Anomes ou ano/mes).")
            st.stop()

    df_inpc = df_inpc.sort_values("Anomes").reset_index(drop=True)
    df_inpc["inpc_fator"] = 1 + df_inpc["inpc_val"] / 100
    df_inpc["inpc_acm"] = df_inpc["inpc_fator"].cumprod()

    df_final["Anomes"] = df_final["competênciamov"].astype(str)
    df_final = pd.merge(df_final, df_inpc[["Anomes", "inpc_acm"]], on="Anomes", how="left")
    df_final["Sal_def_INPC"] = df_final["salário"] / df_final["inpc_acm"]

    df_final["ano"] = df_final["Anomes"].astype(str).str[:4].astype(int)
    df_final["mes"] = df_final["Anomes"].astype(str).str[4:6].astype(int)
    df_final["mes_nome"] = df_final["mes"].map({
        1: "Janeiro", 2: "Fevereiro", 3: "Março", 4: "Abril", 5: "Maio", 6: "Junho",
        7: "Julho", 8: "Agosto", 9: "Setembro", 10: "Outubro", 11: "Novembro", 12: "Dezembro"
    })

    mapa_regiao = {1: "Norte", 2: "Nordeste", 3: "Sudeste", 4: "Sul", 5: "Centro-Oeste"}
    mapa_uf = {
        11: "RO", 12: "AC", 13: "AM", 14: "RR", 15: "PA", 16: "AP", 17: "TO",
        21: "MA", 22: "PI", 23: "CE", 24: "RN", 25: "PB", 26: "PE", 27: "AL", 28: "SE", 29: "BA",
        31: "MG", 32: "ES", 33: "RJ", 35: "SP", 41: "PR", 42: "SC", 43: "RS",
        50: "MS", 51: "MT", 52: "GO", 53: "DF"
    }
    mapa_contrato = {-1: "Demitidos", 1: "Admitidos"}
    mapa_sexo = {1: "Masculino", 3: "Feminino", 9: "Não Identificado"}
    mapa_raca = {1: "Branca", 2: "Preta", 3: "Parda", 4: "Amarela", 5: "Indígena", 6: "Não Informado", 9: "Não Identificado"}

    df_final["nome_regiao"] = df_final["região"].map(mapa_regiao)
    df_final["sigla_uf"] = df_final["uf"].map(mapa_uf)
    df_final["nome_municipio"] = df_final["município"].astype(str)

    if "saldomovimentação" in df_final.columns:
        df_final["contrato"] = df_final["saldomovimentação"].map(mapa_contrato)
    if "sexo" in df_final.columns:
        df_final["genero"] = df_final["sexo"].map(mapa_sexo)
    if "raçacor" in df_final.columns:
        df_final["etnia"] = df_final["raçacor"].map(mapa_raca)

    # ============================================================================
    # SIDEBAR - FILTROS INTERATIVOS
    # ============================================================================
    st.sidebar.header("🔍 Filtros")
    with st.sidebar.expander("📅 Período", expanded=True):
        anos_disponiveis = sorted(df_final["ano"].unique())
        ano_selecionado = st.selectbox("Ano", anos_disponiveis)
        meses_ano = sorted(df_final[df_final["ano"] == ano_selecionado]["mes"].unique())
        meses_nomes = [df_final[df_final["mes"] == m]["mes_nome"].iloc[0] for m in meses_ano]
        mes_idx = st.selectbox("Mês", range(len(meses_nomes)), format_func=lambda x: meses_nomes[x])
        mes_selecionado = meses_ano[mes_idx]

    # (demais filtros, KPIs, gráficos e exportação seguem iguais)

    st.markdown("---")
    st.markdown("""
        <div style="text-align: center; color: gray; font-size: 12px;">
            <p>Dashboard PNAD/CAGED | Desenvolvido por Professor Dulluca | 2026</p>
        </div>
    """, unsafe_allow_html=True)

# ============================================================================
# CAPTURA DE ERROS
# ============================================================================
except Exception as e:
    st.error("❌ Erro ao executar o app:")
    st.code(traceback.format_exc())