# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiwAgQjCSBwxEg5S9rJc67jOnYAE-rtf
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from io import BytesIO
import warnings

warnings.filterwarnings("ignore")

# -*- coding: utf-8 -*-

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from io import BytesIO
import warnings
import traceback

warnings.filterwarnings("ignore")

# ============================================================================
# BLOCO DE CAPTURA DE ERROS
# ============================================================================

try:

    # ============================================================================
    # CONFIGURAÇÃO DA PÁGINA STREAMLIT
    # ============================================================================

    st.set_page_config(
        page_title="Dashboard PNAD/CAGED",
        page_icon="📊",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    st.markdown("""
        <style>
        .main { padding: 2rem; }
        .stMetric { background-color: #f0f2f6; padding: 1rem; border-radius: 0.5rem; }
        </style>
        """, unsafe_allow_html=True)

    # ============================================================================
    # TÍTULO
    # ============================================================================

    st.title("📊 Dashboard Interativo PNAD/CAGED")
    st.markdown("""
        **Análise de Salários, Movimentação e Diversidade no Mercado de Trabalho Brasileiro**
    """)

    # ============================================================================
    # CARREGAMENTO DE DADOS
    # ============================================================================

    @st.cache_data(ttl=3600)
    def carregar_dados_github():
        usuario_github = "pesquisaitr-cmd"
        repo_github = "PNAD"
        branch = "main"

        url_df_final = f"https://raw.githubusercontent.com/{usuario_github}/{repo_github}/{branch}/dados/df_final.parquet"
        url_df_inpc = f"https://raw.githubusercontent.com/{usuario_github}/{repo_github}/{branch}/dados/df_inpc.parquet"

        df_final = pd.read_parquet(url_df_final)
        df_inpc = pd.read_parquet(url_df_inpc)

        return df_final, df_inpc

    df_final, df_inpc = carregar_dados_github()

    # ============================================================================
    # TODO O RESTANTE DO SEU CÓDIGO VEM AQUI
    # (pré-processamento, filtros, gráficos, tabelas, exportação, rodapé)
    # ============================================================================

# ============================================================================
# PRÉ-PROCESSAMENTO DE DADOS
# ============================================================================

# Garantir que df_inpc tem a coluna Anomes
if "Anomes" not in df_inpc.columns:
    if "ano" in df_inpc.columns and "mes" in df_inpc.columns:
        df_inpc["Anomes"] = df_inpc["ano"].astype(str) + df_inpc["mes"].astype(str).str.zfill(2)
    else:
        st.error("❌ df_inpc não possui as colunas esperadas (Anomes ou ano/mes).")
        st.stop()

# Calcular INPC acumulado
df_inpc = df_inpc.sort_values("Anomes").reset_index(drop=True)
df_inpc["inpc_fator"] = 1 + df_inpc["inpc_val"] / 100
df_inpc["inpc_acm"] = df_inpc["inpc_fator"].cumprod()

# Preparar df_final
df_final["Anomes"] = df_final["competênciamov"].astype(str)
df_final = pd.merge(df_final, df_inpc[["Anomes", "inpc_acm"]], on="Anomes", how="left")
df_final["Sal_def_INPC"] = df_final["salário"] / df_final["inpc_acm"]

# Extrair ano e mês
df_final["ano"] = df_final["Anomes"].astype(str).str[:4].astype(int)
df_final["mes"] = df_final["Anomes"].astype(str).str[4:6].astype(int)
df_final["mes_nome"] = df_final["mes"].map({
    1: "Janeiro", 2: "Fevereiro", 3: "Março", 4: "Abril", 5: "Maio", 6: "Junho",
    7: "Julho", 8: "Agosto", 9: "Setembro", 10: "Outubro", 11: "Novembro", 12: "Dezembro"
})

# Mapear códigos para nomes
mapa_regiao = {1: "Norte", 2: "Nordeste", 3: "Sudeste", 4: "Sul", 5: "Centro-Oeste"}
mapa_uf = {
    11: "RO", 12: "AC", 13: "AM", 14: "RR", 15: "PA", 16: "AP", 17: "TO",
    21: "MA", 22: "PI", 23: "CE", 24: "RN", 25: "PB", 26: "PE", 27: "AL", 28: "SE", 29: "BA",
    31: "MG", 32: "ES", 33: "RJ", 35: "SP", 41: "PR", 42: "SC", 43: "RS",
    50: "MS", 51: "MT", 52: "GO", 53: "DF"
}
mapa_contrato = {-1: "Demitidos", 1: "Admitidos"}
mapa_sexo = {1: "Masculino", 3: "Feminino", 9: "Não Identificado"}
mapa_raca = {1: "Branca", 2: "Preta", 3: "Parda", 4: "Amarela", 5: "Indígena", 6: "Não Informado", 9: "Não Identificado"}

if df_final["região"].dtype == "int64":
    df_final["nome_regiao"] = df_final["região"].map(mapa_regiao)
else:
    df_final["nome_regiao"] = df_final["região"]

if df_final["uf"].dtype == "int64":
    df_final["sigla_uf"] = df_final["uf"].map(mapa_uf)
else:
    df_final["sigla_uf"] = df_final["uf"]

df_final["nome_municipio"] = df_final["município"].astype(str)

if "saldomovimentação" in df_final.columns:
    df_final["contrato"] = df_final["saldomovimentação"].map(mapa_contrato)

if "sexo" in df_final.columns:
    df_final["genero"] = df_final["sexo"].map(mapa_sexo)

if "raçacor" in df_final.columns:
    df_final["etnia"] = df_final["raçacor"].map(mapa_raca)

# ============================================================================
# SIDEBAR - FILTROS INTERATIVOS
# ============================================================================

st.sidebar.header("🔍 Filtros")

# Seção de Período
with st.sidebar.expander("📅 Período", expanded=True):
    anos_disponiveis = sorted(df_final["ano"].unique())
    ano_selecionado = st.selectbox("Ano", anos_disponiveis, key="ano_select")

    meses_ano = sorted(df_final[df_final["ano"] == ano_selecionado]["mes"].unique())
    meses_nomes = [df_final[df_final["mes"] == m]["mes_nome"].iloc[0] for m in meses_ano]
    mes_selecionado_idx = st.selectbox("Mês", range(len(meses_nomes)), format_func=lambda x: meses_nomes[x], key="mes_select")
    mes_selecionado = meses_ano[mes_selecionado_idx]

# Seção de Localização
with st.sidebar.expander("🗺️ Localização", expanded=True):
    regioes_disponiveis = sorted(df_final["nome_regiao"].unique())
    regiao_selecionada = st.selectbox("Região", ["Todas"] + regioes_disponiveis, key="regiao_select")

    if regiao_selecionada == "Todas":
        ufs_disponiveis = sorted(df_final["sigla_uf"].unique())
    else:
        ufs_disponiveis = sorted(df_final[df_final["nome_regiao"] == regiao_selecionada]["sigla_uf"].unique())

    uf_selecionada = st.selectbox("UF", ["Todos"] + ufs_disponiveis, key="uf_select")

    if uf_selecionada == "Todos":
        municipios_disponiveis = sorted(df_final["nome_municipio"].unique())
    else:
        municipios_disponiveis = sorted(df_final[df_final["sigla_uf"] == uf_selecionada]["nome_municipio"].unique())

    municipio_selecionado = st.selectbox("Município", ["Todos"] + municipios_disponiveis, key="municipio_select")

# Seção de Ocupação
with st.sidebar.expander("💼 Ocupação", expanded=False):
    cbos_disponiveis = sorted(df_final["cbo2002ocupação"].unique())
    cbo_selecionado = st.selectbox("CBO", ["Todos"] + cbos_disponiveis, key="cbo_select")

# Seção de Diversidade
with st.sidebar.expander("🌈 Diversidade", expanded=False):
    if "genero" in df_final.columns:
        generos_disponiveis = sorted(df_final["genero"].unique())
        genero_selecionado = st.selectbox("Gênero", ["Todos"] + generos_disponiveis, key="genero_select")
    else:
        genero_selecionado = "Todos"

    if "etnia" in df_final.columns:
        etnias_disponiveis = sorted(df_final["etnia"].unique())
        etnia_selecionada = st.selectbox("Etnia", ["Todos"] + etnias_disponiveis, key="etnia_select")
    else:
        etnia_selecionada = "Todos"

# ============================================================================
# APLICAR FILTROS
# ============================================================================

df_filtrado = df_final[
    (df_final["ano"] == ano_selecionado) &
    (df_final["mes"] == mes_selecionado)
].copy()

if regiao_selecionada != "Todas":
    df_filtrado = df_filtrado[df_filtrado["nome_regiao"] == regiao_selecionada]

if uf_selecionada != "Todos":
    df_filtrado = df_filtrado[df_filtrado["sigla_uf"] == uf_selecionada]

if municipio_selecionado != "Todos":
    df_filtrado = df_filtrado[df_filtrado["nome_municipio"] == municipio_selecionado]

if cbo_selecionado != "Todos":
    df_filtrado = df_filtrado[df_filtrado["cbo2002ocupação"] == cbo_selecionado]

if genero_selecionado != "Todos" and "genero" in df_filtrado.columns:
    df_filtrado = df_filtrado[df_filtrado["genero"] == genero_selecionado]

if etnia_selecionada != "Todos" and "etnia" in df_filtrado.columns:
    df_filtrado = df_filtrado[df_filtrado["etnia"] == etnia_selecionada]

# ============================================================================
# MÉTRICAS PRINCIPAIS (KPIs)
# ============================================================================

st.subheader("📈 Indicadores Principais")

col1, col2, col3, col4 = st.columns(4)

with col1:
    total_admitidos = len(df_filtrado[df_filtrado["contrato"] == "Admitidos"]) if "contrato" in df_filtrado.columns else 0
    st.metric("Total Admitidos", f"{int(total_admitidos):,}")

with col2:
    total_demitidos = len(df_filtrado[df_filtrado["contrato"] == "Demitidos"]) if "contrato" in df_filtrado.columns else 0
    st.metric("Total Demitidos", f"{int(total_demitidos):,}")

with col3:
    saldo = total_admitidos - total_demitidos
    st.metric("Saldo", f"{int(saldo):,}")

with col4:
    media_salarial = df_filtrado["salário"].mean()
    st.metric("Salário Médio", f"R$ {media_salarial:,.2f}")

# ============================================================================
# GRÁFICOS PRINCIPAIS
# ============================================================================

st.subheader("📊 Visualizações Interativas")

tab1, tab2, tab3, tab4, tab5 = st.tabs(
    ["Salários", "Por Região", "Por Gênero", "Por Etnia", "Comparativo"]
)

try:
    with tab1:
        st.markdown("**Média Salarial por Tipo de Movimentação**")
        if "contrato" in df_filtrado.columns and len(df_filtrado) > 0:
            df_media = df_filtrado.groupby("contrato").agg({"salário": "mean", "Sal_def_INPC": "mean"}).reset_index()
            fig = go.Figure()
            fig.add_trace(go.Bar(x=df_media["contrato"], y=df_media["salário"], name="Nominal", marker_color="lightblue"))
            fig.add_trace(go.Bar(x=df_media["contrato"], y=df_media["Sal_def_INPC"], name="Deflacionado", marker_color="darkblue"))
            fig.update_layout(title="Salários por Movimentação", height=400, barmode="group")
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab2:
        st.markdown("**Movimentação por Região**")
        if "nome_regiao" in df_filtrado.columns and len(df_filtrado) > 0:
            df_regiao = df_filtrado.groupby(["nome_regiao", "contrato"]).size().reset_index(name="quantidade")
            fig = px.bar(df_regiao, x="nome_regiao", y="quantidade", color="contrato", barmode="group", height=400)
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab3:
        st.markdown("**Distribuição por Gênero**")
        if "genero" in df_filtrado.columns and len(df_filtrado) > 0:
            df_genero = df_filtrado.groupby("genero").size().reset_index(name="quantidade")
            fig = px.pie(df_genero, values="quantidade", names="genero", hole=0.3, height=400)
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab4:
        st.markdown("**Movimentação por Raça/Cor**")
        if "etnia" in df_filtrado.columns and len(df_filtrado) > 0:
            df_etnia = df_filtrado.groupby(["etnia", "contrato"]).size().reset_index(name="quantidade")
            fig = px.bar(df_etnia, x="etnia", y="quantidade", color="contrato", barmode="stack", height=400)
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab5:
        st.markdown("**Análise Comparativa**")
        if "contrato" in df_filtrado.columns and len(df_filtrado) > 0:
            df_comp = df_filtrado.groupby("contrato").agg({"salário": "mean", "Anomes": "count"}).reset_index().rename(columns={"Anomes": "quantidade"})
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=df_comp["contrato"], y=df_comp["salário"], mode="lines+markers", name="Salário", yaxis="y1"))
            fig.add_trace(go.Bar(x=df_comp["contrato"], y=df_comp["quantidade"], name="Quantidade", yaxis="y2", opacity=0.5))
            fig.update_layout(yaxis=dict(title="Salário"), yaxis2=dict(title="Quantidade", overlaying="y", side="right"), height=400)
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

except Exception as e:
    st.error(f"❌ Erro ao gerar gráficos: {e}")

# ============================================================================
# TABELA DE DADOS
# ============================================================================

st.subheader("📋 Dados Detalhados")

if st.checkbox("Mostrar tabela de dados", value=False):
    colunas_exibir = [col for col in ["Anomes", "nome_regiao", "sigla_uf", "nome_municipio", "cbo2002ocupação", "contrato", "genero", "etnia", "salário", "Sal_def_INPC"] if col in df_filtrado.columns]
    st.dataframe(df_filtrado[colunas_exibir], use_container_width=True)

# ============================================================================
# EXPORTAR DADOS
# ============================================================================

st.subheader("💾 Exportar Dados")

col_csv, col_excel = st.columns(2)

with col_csv:
    if st.button("📥 Baixar como CSV"):
        csv = df_filtrado.to_csv(index=False, encoding="utf-8")
        st.download_button(label="Download CSV", data=csv, file_name=f"dados_{ano_selecionado}_{mes_selecionado:02d}.csv", mime="text/csv")

with col_excel:
    if st.button("📥 Baixar como Excel"):
        buffer = BytesIO()
        with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
            df_filtrado.to_excel(writer, index=False, sheet_name="Dados")
        buffer.seek(0)
        st.download_button(label="Download Excel", data=buffer.getvalue(), file_name=f"dados_{ano_selecionado}_{mes_selecionado:02d}.xlsx", mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

# ============================================================================
# RODAPÉ
# ============================================================================

st.markdown("---")
st.markdown("""
    <div style="text-align: center; color: gray; font-size: 12px;">
        <p>Dashboard PNAD/CAGED | Desenvolvido por Professor Dulluca | 2026</p>
        <p>Dados lidos diretamente do GitHub | 100% Gratuito</p>
    </div>
""", unsafe_allow_html=True)