# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiwAgQjCSBwxEg5S9rJc67jOnYAE-rtf
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from io import BytesIO
import warnings
import traceback

warnings.filterwarnings("ignore")

# ============================================================================
# BLOCO DE CAPTURA DE ERROS
# ============================================================================

try:

    # ============================================================================
    # CONFIGURAÇÃO DA PÁGINA STREAMLIT
    # ============================================================================
    st.set_page_config(
        page_title="Dashboard PNAD/CAGED",
        page_icon="📊",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    st.markdown("""
        <style>
        .main { padding: 2rem; }
        .stMetric { background-color: #f0f2f6; padding: 1rem; border-radius: 0.5rem; }
        </style>
        """, unsafe_allow_html=True)

    # ============================================================================
    # TÍTULO
    # ============================================================================
    st.title("📊 Dashboard Interativo PNAD/CAGED")
    st.markdown("""
        **Análise de Salários, Movimentação e Diversidade no Mercado de Trabalho Brasileiro**
    """)

    # ============================================================================
    # CARREGAMENTO DE DADOS
    # ============================================================================
    @st.cache_data(ttl=3600)
    def carregar_dados_github():
        url_df_final_1 = "https://raw.githubusercontent.com/pesquisaitr-cmd/PNAD/main/dados/df_final_1.parquet"
        url_df_final_2 = "https://raw.githubusercontent.com/pesquisaitr-cmd/PNAD/main/dados/df_final_2.parquet"
        url_df_final_3 = "https://raw.githubusercontent.com/pesquisaitr-cmd/PNAD/main/dados/df_final_3.parquet"
        url_df_inpc = "https://raw.githubusercontent.com/pesquisaitr-cmd/PNAD/main/dados/df_inpc.parquet"

        # Carregar os 3 pedaços
        df1 = pd.read_parquet(url_df_final_1)
        df2 = pd.read_parquet(url_df_final_2)
        df3 = pd.read_parquet(url_df_final_3)

        # Concatenar
        df_final = pd.concat([df1, df2, df3], ignore_index=True)

        # Carregar INPC
        df_inpc = pd.read_parquet(url_df_inpc)

        return df_final, df_inpc

    df_final, df_inpc = carregar_dados_github()

    # ============================================================================
    # PRÉ-PROCESSAMENTO
    # ============================================================================
    if "Anomes" not in df_inpc.columns:
        if "ano" in df_inpc.columns and "mes" in df_inpc.columns:
            df_inpc["Anomes"] = df_inpc["ano"].astype(str) + df_inpc["mes"].astype(str).str.zfill(2)
        else:
            st.error("❌ df_inpc não possui as colunas esperadas (Anomes ou ano/mes).")
            st.stop()

    df_inpc = df_inpc.sort_values("Anomes").reset_index(drop=True)
    df_inpc["inpc_fator"] = 1 + df_inpc["inpc_val"] / 100
    df_inpc["inpc_acm"] = df_inpc["inpc_fator"].cumprod()

    df_final["Anomes"] = df_final["competênciamov"].astype(str)
    df_final = pd.merge(df_final, df_inpc[["Anomes", "inpc_acm"]], on="Anomes", how="left")
    df_final["Sal_def_INPC"] = df_final["salário"] / df_final["inpc_acm"]

    df_final["ano"] = df_final["Anomes"].astype(str).str[:4].astype(int)
    df_final["mes"] = df_final["Anomes"].astype(str).str[4:6].astype(int)
    df_final["mes_nome"] = df_final["mes"].map({
        1: "Janeiro", 2: "Fevereiro", 3: "Março", 4: "Abril", 5: "Maio", 6: "Junho",
        7: "Julho", 8: "Agosto", 9: "Setembro", 10: "Outubro", 11: "Novembro", 12: "Dezembro"
    })

    mapa_regiao = {1: "Norte", 2: "Nordeste", 3: "Sudeste", 4: "Sul", 5: "Centro-Oeste"}
    mapa_uf = {
        11: "RO", 12: "AC", 13: "AM", 14: "RR", 15: "PA", 16: "AP", 17: "TO",
        21: "MA", 22: "PI", 23: "CE", 24: "RN", 25: "PB", 26: "PE", 27: "AL", 28: "SE", 29: "BA",
        31: "MG", 32: "ES", 33: "RJ", 35: "SP", 41: "PR", 42: "SC", 43: "RS",
        50: "MS", 51: "MT", 52: "GO", 53: "DF"
    }
    mapa_contrato = {-1: "Demitidos", 1: "Admitidos"}
    mapa_sexo = {1: "Masculino", 3: "Feminino", 9: "Não Identificado"}
    mapa_raca = {1: "Branca", 2: "Preta", 3: "Parda", 4: "Amarela", 5: "Indígena", 6: "Não Informado", 9: "Não Identificado"}

    df_final["nome_regiao"] = df_final["região"].map(mapa_regiao)
    df_final["sigla_uf"] = df_final["uf"].map(mapa_uf)
    df_final["nome_municipio"] = df_final["município"].astype(str)

    if "saldomovimentação" in df_final.columns:
        df_final["contrato"] = df_final["saldomovimentação"].map(mapa_contrato)
    if "sexo" in df_final.columns:
        df_final["genero"] = df_final["sexo"].map(mapa_sexo)
    if "raçacor" in df_final.columns:
        df_final["etnia"] = df_final["raçacor"].map(mapa_raca)

    # ============================================================================
    # SIDEBAR
    # ============================================================================
    st.sidebar.header("🔍 Filtros")

    with st.sidebar.expander("📅 Período", expanded=True):
        anos_disponiveis = sorted(df_final["ano"].unique())
        ano_selecionado = st.selectbox("Ano", anos_disponiveis)

        meses_ano = sorted(df_final[df_final["ano"] == ano_selecionado]["mes"].unique())
        meses_nomes = [df_final[df_final["mes"] == m]["mes_nome"].iloc[0] for m in meses_ano]
        mes_idx = st.selectbox("Mês", range(len(meses_nomes)), format_func=lambda x: meses_nomes[x])
        mes_selecionado = meses_ano[mes_idx]

    with st.sidebar.expander("🗺️ Localização", expanded=True):
        regioes = sorted(df_final["nome_regiao"].unique())
        regiao = st.selectbox("Região", ["Todas"] + regioes)

        if regiao == "Todas":
            ufs = sorted(df_final["sigla_uf"].unique())
        else:
            ufs = sorted(df_final[df_final["nome_regiao"] == regiao]["sigla_uf"].unique())

        uf = st.selectbox("UF", ["Todos"] + ufs)

        if uf == "Todos":
            municipios = sorted(df_final["nome_municipio"].unique())
        else:
            municipios = sorted(df_final[df_final["sigla_uf"] == uf]["nome_municipio"].unique())

        municipio = st.selectbox("Município", ["Todos"] + municipios)

    with st.sidebar.expander("💼 Ocupação"):
        cbos = sorted(df_final["cbo2002ocupação"].unique())
        cbo = st.selectbox("CBO", ["Todos"] + cbos)

    with st.sidebar.expander("🌈 Diversidade"):
        generos = sorted(df_final["genero"].unique()) if "genero" in df_final.columns else []
        genero = st.selectbox("Gênero", ["Todos"] + generos)

        etnias = sorted(df_final["etnia"].unique()) if "etnia" in df_final.columns else []
        etnia = st.selectbox("Etnia", ["Todos"] + etnias)

    # ============================================================================
    # FILTRAGEM
    # ============================================================================
    df_filtrado = df_final[
        (df_final["ano"] == ano_selecionado) &
        (df_final["mes"] == mes_selecionado)
    ].copy()

    if regiao != "Todas":
        df_filtrado = df_filtrado[df_filtrado["nome_regiao"] == regiao]

    if uf != "Todos":
        df_filtrado = df_filtrado[df_filtrado["sigla_uf"] == uf]

    if municipio != "Todos":
        df_filtrado = df_filtrado[df_filtrado["nome_municipio"] == municipio]

    if cbo != "Todos":
        df_filtrado = df_filtrado[df_filtrado["cbo2002ocupação"] == cbo]

    if genero != "Todos":
        df_filtrado = df_filtrado[df_filtrado["genero"] == genero]

    if etnia != "Todos":
        df_filtrado = df_filtrado[df_filtrado["etnia"] == etnia]

    # ============================================================================
    # KPIs
    # ============================================================================
    st.subheader("📈 Indicadores Principais")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        total_adm = len(df_filtrado[df_filtrado["contrato"] == "Admitidos"])
        st.metric("Total Admitidos", f"{total_adm:,}")

    with col2:
        total_dem = len(df_filtrado[df_filtrado["contrato"] == "Demitidos"])
        st.metric("Total Demitidos", f"{total_dem:,}")

    with col3:
        saldo = total_adm - total_dem
        st.metric("Saldo", f"{saldo:,}")

    with col4:
        media_sal = df_filtrado["salário"].mean()
        st.metric("Salário Médio", f"R$ {media_sal:,.2f}")

    # ============================================================================
    # GRÁFICOS
    # ============================================================================
    st.subheader("📊 Visualizações Interativas")

    tab1, tab2, tab3, tab4, tab5 = st.tabs(
        ["Salários", "Por Região", "Por Gênero", "Por Etnia", "Comparativo"]
    )

    with tab1:
        if len(df_filtrado) > 0:
            df_media = df_filtrado.groupby("contrato").agg({"salário": "mean", "Sal_def_INPC": "mean"}).reset_index()
            fig = go.Figure()
            fig.add_trace(go.Bar(x=df_media["contrato"], y=df_media["salário"], name="Nominal"))
            fig.add_trace(go.Bar(x=df_media["contrato"], y=df_media["Sal_def_INPC"], name="Deflacionado"))
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab2:
        if len(df_filtrado) > 0:
            df_regiao = df_filtrado.groupby(["nome_regiao", "contrato"]).size().reset_index(name="quantidade")
            fig = px.bar(df_regiao, x="nome_regiao", y="quantidade", color="contrato", barmode="group")
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab3:
        if len(df_filtrado) > 0:
            df_genero = df_filtrado.groupby("genero").size().reset_index(name="quantidade")
            fig = px.pie(df_genero, values="quantidade", names="genero", hole=0.3)
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab4:
        if len(df_filtrado) > 0:
            df_etnia = df_filtrado.groupby(["etnia", "contrato"]).size().reset_index(name="quantidade")
            fig = px.bar(df_etnia, x="etnia", y="quantidade", color="contrato", barmode="stack")
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    with tab5:
        if len(df_filtrado) > 0:
            df_comp = df_filtrado.groupby("contrato").agg({"salário": "mean", "Anomes": "count"}).reset_index()
            df_comp.rename(columns={"Anomes": "quantidade"}, inplace=True)

            fig = go.Figure()
            fig.add_trace(go.Scatter(x=df_comp["contrato"], y=df_comp["salário"], mode="lines+markers", name="Salário"))
            fig.add_trace(go.Bar(x=df_comp["contrato"], y=df_comp["quantidade"], name="Quantidade", opacity=0.5))
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sem dados para este período.")

    # ============================================================================
    # TABELA
    # ============================================================================
    st.subheader("📋 Dados Detalhados")

    if st.checkbox("Mostrar tabela de dados"):
        colunas = ["Anomes", "nome_regiao", "sigla_uf", "nome_municipio",
                   "cbo2002ocupação", "contrato", "genero", "etnia",
                   "salário", "Sal_def_INPC"]
        colunas = [c for c in colunas if c in df_filtrado.columns]
        st.dataframe(df_filtrado[colunas], use_container_width=True)

    # ============================================================================
    # EXPORTAÇÃO
    # ============================================================================
    st.subheader("💾 Exportar Dados")

    col_csv, col_excel = st.columns(2)

    with col_csv:
        if st.button("📥 Baixar como CSV"):
            csv = df_filtrado.to_csv(index=False, encoding="utf-8")
            st.download_button("Download CSV", csv, file_name="dados.csv")

    with col_excel:
        if st.button("📥 Baixar como Excel"):
            buffer = BytesIO()
            with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
                df_filtrado.to_excel(writer, index=False)
            st.download_button("Download Excel", buffer.getvalue(), file_name="dados.xlsx")

    # ============================================================================
    # RODAPÉ
    # ============================================================================
    st.markdown("---")
    st.markdown("""
        <div style="text-align: center; color: gray; font-size: 12px;">
            <p>Dashboard PNAD/CAGED | Desenvolvido por Professor Dulluca | 2026</p>
        </div>
    """, unsafe_allow_html=True)

# ============================================================================
# CAPTURA DE ERROS
# ============================================================================
except Exception as e:
    st.error("❌ Erro ao executar o app:")
    st.code(traceback.format_exc())